version: "3.7"

services:
  vue-ui:
    build:
      context: ./vue-ui
      dockerfile: Dockerfile
    depends_on:
      - temporary_backend
      - backend
    ports:
      - "8080:8080"
    command:
      - |
        npm ci
        npm run serve
    entrypoint: "/bin/bash -c"
    volumes:
      - ./vue-ui/src:/app/src

  temporary_backend:
    build:
      context: ./temporary_backend
      dockerfile: Dockerfile
    ports:
      - "1357:1357"
      - "1369:1369"
    entrypoint: "/bin/bash -c"
    volumes:
      - ./temporary_backend/:/app
    command:
      - |
        npm ci
        npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      DATABASE__PSQL_PASSWORD: "${POSTGRES_PASSWORD}"

  postgresql:
    image: mdillon/postgis:9.5-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - "postgresql:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: howtohelppeople
      POSTGRES_DB: howtohelppeople
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  postgresql:
    driver: local
