version: '3'

services:
  postgresql:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: howtohelppeople
      POSTGRES_DB: howtohelppeople
      POSTGRES_PASSWORD: howtohelppeople!2020
